on:
  push:
    branches: 
      - main
name: AzureConnect
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az group list
    - name: "example-cron-action"
  on:
  schedule:
    - cron:  '*/30 * * * *'    
  jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }} 
      - name: Do some work
        run: echo $GITHUB_SHA
      - name: Remove scheduled job
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: ${{ secrets.WORKFLOWS_TOKEN }} 

