name: Docker File Creation

on:
  push:
    branches: [ ACR ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: pull request
      if: github.event_name == 'pull_request' && github.event.action == 'merge only when contents modified' && github.event.pull_request.merged == true
